using System; 

namespace Game_engine_Obscure.API.HerrorHandler; 

class ILoveCorrectPeapol // >:3 
{
    public static String MapGen_Error_1 = "MapGen [1] : Invalid BaseMidpoint Cordinates on external"; // MapGen: Null External or Internal declaration of map generation
}

class ILoveHandlingErrors // :3
{
    public static bool Catch_Null(bool? Catch_Data)
    {
        return Catch_Data.HasValue; 
    }
}